title: Dennis Gluesenkamp
logo: /IMG/dgluesen.jpg

description: >
  <br><br>
  <strong>Data Strategist // Data Scientist</strong>
  <br>
  <strong>Greater Cologne/Duesseldorf area, Germany</strong>
  <br><br><br>
  Currently employed with a wholesale group as people analytics expert// Several years of experience in the insurance industry // Excited in sports analytics
  <br><br><br>
  MSc in BI Systems & Data Mining<br>
  <a title="@ DMU Leicester" href="https://www.dmu.ac.uk/" target="_blank" rel="noopener">DMU Leicester</a>
  <br>Diplom (equiv. to MSc) in Physics<br>
  <a title="@ U Bonn" href="https://www.uni-bonn.de/" target="_blank" rel="noopener">U Bonn</a>
  <br><br><br><br>
  <center>
  <a title="linkedin.com/in/dennisgluesenkamp" href="https://linkedin.com/in/dennisgluesenkamp" target="_blank" rel="noopener"><img src="https://cdn3.iconfinder.com/data/icons/social-media-2253/17/Vector-4-128.png" alt="" hspace=10 width="28" height="28" /></a>
  <a title="@dgluesen" href="https://twitter.com/dgluesen" target="_blank" rel="noopener"><img src="https://cdn3.iconfinder.com/data/icons/social-media-2253/17/Vector-3-128.png" alt="" hspace=10 width="32" height="28" /></a>
  <a title="@dgluesen" href="https://instagram.com/dgluesen" target="_blank" rel="noopener"><img src="https://cdn3.iconfinder.com/data/icons/social-media-2253/17/Vector-1-128.png" alt="" hspace=10 width="28" height="28" /></a>
  <a title="@dgluesen" href="https://github.com/dgluesen" target="_blank" rel="noopener"><img src="https://cdn3.iconfinder.com/data/icons/social-media-2253/25/Group-512.png" alt="" hspace=10 width="28" height="28" /></a>
  </center>
  <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

show_downloads: false
theme: jekyll-theme-minimal
